/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PracticeSettings: typeof import('./src/components/PracticeSettings.vue')['default']
    QuestionArea: typeof import('./src/components/QuestionArea.vue')['default']
    QuestionNavigator: typeof import('./src/components/QuestionNavigator.vue')['default']
    ResultsPage: typeof import('./src/components/ResultsPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WrongQuestionsManager: typeof import('./src/components/WrongQuestionsManager.vue')['default']
  }
}
